# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: marcimastro98.Xenon
PackageVersion: 4.11.8
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
